recital1 = [
    {
      "": 1,
      "Nombre": "Víctor Ariel Ortega Lugo",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 5,
      "Nivel": "FPA 1\nU1",
      "Repertorio": "1. El reloj viejo\n 2. El equilibrista\n3. El caracol\n4. El eco",
      "Duración": 5
    },
    {
      "": 2,
      "Nombre": "Diego González León",
      "Escuela": "Orquestarte",
      "Docente": "David",
      "Edad": 7,
      "Nivel": "Deditos",
      "Repertorio": "1. Fiesta de cumpleaños\n2. El cartero\n3. Barquitos de papel\n4. Campanas",
      "Duración": 3
    },
    {
      "": 3,
      "Nombre": "Miriam Judith Muñiz Puc",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 12,
      "Nivel": "FPA 2\nTERMINADO",
      "Repertorio": "1. Pequeña serenata nocturna\n2. Dos pequeñas marchas: un desfile bajo el sol y un desfile bajo la lluvia.\n3. Una melodía de Beethoven \n4. Sonatina en miniatura: Primer y Segundo Movimiento",
      "Duración": 5
    },
    {
      "": 5,
      "Nombre": "Víctor Ariel Ortega Lugo",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": "",
      "Nivel": "FPA 1\nU1",
      "Repertorio": "5. Mi primer estudio\n6. Brillan las estrellas\n7. Dos por Diez\n8. El granjero",
      "Duración": 5
    },
    {
      "": 6,
      "Nombre": "Matías Cáceres Pérez",
      "Escuela": "Clapping",
      "Docente": "Andrea",
      "Edad": "",
      "Nivel": "FPA 2\nU1",
      "Repertorio": "1. El ratoncito de la casa embrujada\n2. Danza clásica\n3. El cazador\n4. El potro salvaje",
      "Duración": 5
    },
    {
      "": 7,
      "Nombre": "Carlos Enrique Morales Castro",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 8,
      "Nivel": "FPA 1\nTERMINADO",
      "Repertorio": "1. Tai-chi en la mañana\n2. Suenan las cornetas\n3. ¿Princesa o monstruo?\n4. Duérmete niño \n5. ¿Qué compro? \n6. Yankee Doodle",
      "Duración": 6
    },
    {
      "": 8,
      "Nombre": "Martha González León",
      "Escuela": "Orquestarte",
      "Docente": "David",
      "Edad": 12,
      "Nivel": "Thomson grado 1",
      "Repertorio": "1. Music Land\n2. Patterns\n3. Run-Away River\n4. Swans on the lake\n5. The Scissors grinder",
      "Duración": 5
    },
    {
      "": 9,
      "Nombre": "Miriam Judith Muñiz Puc",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 12,
      "Nivel": "FPA 2\nTERMINADO",
      "Repertorio": "5. Yo siento el ritmo \n6. El espantapájaros \n7. Viaje en Camello \n8. Príncipe Sapo ",
      "Duración": 4
    },
    {
      "": 10,
      "Nombre": "Carlos Enrique Morales Castro",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 8,
      "Nivel": "FPA 1\nTERMINADO",
      "Repertorio": "7. El estudio del Sr. Köhler \n8. Toque de trompetas\n9. Lluvia, ¡vete ya!\n10. Gran Celebración\n11. A Little Night of Music\n12.Tema de Sonic",
      "Duración": 6
    },
    {
      "": "",
      "Nombre": "Martha González León",
      "Escuela": "Orquestarte",
      "Docente": "David",
      "Edad": 12,
      "Nivel": "Thomson grado 1",
      "Repertorio": "6. The man in the moon\n7. The robin\n8. The cuckoo \n9. Stepping  Stones\n10. Little Spring Song",
      "Duración": 6.5
    },
    {
      "": 11,
      "Nombre": "Ana Sophia Anayegui Piña",
      "Escuela": "Clapping",
      "Docente": "Andrea",
      "Edad": "",
      "Nivel": "FPA 2\nU5",
      "Repertorio": "1. Una canción confusa\n2. La flauta andina\n3. Una marcha alegre\n4. Una vez hubo un juez\n5. La leyenda del búfalo",
      "Duración": 6
    },
    {
      "": 12,
      "Nombre": "Miriam Judith Muñiz Puc",
      "Escuela": "Clapping",
      "Docente": "Arleni",
      "Edad": 12,
      "Nivel": "FPA 2\nTERMINADO",
      "Repertorio": "9. La danza del dinosaurio \n10. El puente de Aviñón \n11. El tranvía \n12. El globo de chicle",
      "Duración": 4
    },
    {
      "": 13,
      "Nombre": "Arleni y David",
      "Escuela": "",
      "Docente": "",
      "Edad": "",
      "Nivel": "",
      "Repertorio": "El jardín encantado",
      "Duración": 3
    },
  ]
recital2 = [
  {
    "": 1,
    "Nombre": "Mauricio Echeverría Lacarriere",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 18,
    "Nivel": "FPA 1\nU1",
    "Repertorio": "1. El reloj viejo\n2. El equilibrista\n3. El caracol\n4. Los marcianos",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": 3,
    "Pago": "Pagado"
  },
  {
    "": 2,
    "Nombre": "Luciana Medina Aguilar",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 11,
    "Nivel": "FPA 2\nU2",
    "Repertorio": "1. Vamos a navegar\n2. El ratoncito de la casa embrujada\n3. Danza clásica\n4. El cazador\n5. La luciérnaga",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nPendiente",
    "Boletos \nExtras": "Pendientes",
    "Pago": "1 cuota"
  },
  {
    "": 3,
    "Nombre": "Liuva Valeria Ortiz Cortés",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 1\nU1",
    "Repertorio": "1. El reloj viejo\n2. El equilibrista\n3. El caracol\n4. Mi primer estudio",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 4,
    "Nombre": "Mauricio Echeverría Lacarriere",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 18,
    "Nivel": "FPA 1\nU1",
    "Repertorio": "1. Remando por el mar\n2. El zapatero\n3. Vamos a jugar\n4. Estrellita\n5. Mi invento",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": 3,
    "Pago": "Pagado"
  },
  {
    "": 5,
    "Nombre": "Adrián Vallejo Azueta",
    "Escuela": "Clapping",
    "Docente": "Andrea",
    "Edad": 9,
    "Nivel": "FPA 4",
    "Repertorio": "1. Sonidos de la fábrica de gomitas\n2. Sonatina\n3. El jinete español",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 6,
    "Nombre": "Jimena Mendoza Medina",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 14,
    "Nivel": "Piano \nIntermedio",
    "Repertorio": "1. Je te laisserai des mots\n2. Arabesque",
    "Duración": 3,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": 1,
    "Pago": "Pagado"
  },
  {
    "": 7,
    "Nombre": "Liuva Valeria Ortiz Cortés",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 1\nU1",
    "Repertorio": "5. El eco\n6. El granjero\n7. Brillan las estrellas\n8. Remando por el mar",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 8,
    "Nombre": "Gabriel Pescador Saavedra",
    "Escuela": "Clapping",
    "Docente": "Andrea",
    "Edad": 1,
    "Nivel": "FPA 4",
    "Repertorio": "1. Para Elisa",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 9,
    "Nombre": "Luciana Medina Aguilar",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 11,
    "Nivel": "FPA 2\nU2",
    "Repertorio": "6. Vamos a la mar\n7. El ratoncito busca el queso\n8. El potro salvaje\n9. La tienda de los relojes\n10. Genshin impact",
    "Duración": 5,
    "Horario \nAsinagdo": "5:30\nPendiente",
    "Boletos \nExtras": "Pendientes",
    "Pago": "1 cuota"
  },
  {
    "": 10,
    "Nombre": "Adrián Vallejo Azueta",
    "Escuela": "Clapping",
    "Docente": "Andrea",
    "Edad": 9,
    "Nivel": "FPA 4",
    "Repertorio": "4. La caza del dragón\n5. De colores\n6. Aria (de la Traviata)",
    "Duración": 4,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 11,
    "Nombre": "Jimena Mendoza Medina",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 14,
    "Nivel": "Piano \nIntermedio",
    "Repertorio": "1. Minueto en sol menor\n2. Estudio en la menor",
    "Duración": 3,
    "Horario \nAsinagdo": "5:30\nConfirmado",
    "Boletos \nExtras": 1,
    "Pago": "Pagado"
  },
]
recital3 = [
  {
    "": 1,
    "Nombre": "Edwin Daniel Figueroa Ovando",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 7,
    "Nivel": "FPA 1\nU1",
    "Repertorio": "1. El equilibrista\n2. El caracol\n3. Mi primer estudio\n4. El eco",
    "Duración": 5,
    "Horario \nAsinagdo": "7:00\nPendiente",
    "Boletos \nExtras": "No",
    "Pago": "Pagado"
  },
  {
    "": 2,
    "Nombre": "Lena Priscila Díaz Escalante",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 9,
    "Nivel": "FPA 1\nTERMINADO",
    "Repertorio": "1. El estudio del Sr. Köhler \n2. Toque de trompetas \n3. Oompa-Loompa \n4. Little Night of Music",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes\n9",
    "Pago": "Pagado"
  },
  {
    "": 3,
    "Nombre": "Shaina Celeste Pérez Cardeña",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 10,
    "Nivel": "FPA 2\nU1",
    "Repertorio": "1. Danza clásica\n2. La luciérnaga\n3. La rueda de la fortuna",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "1 cuota"
  },
  {
    "": 4,
    "Nombre": "Isabella Cabrera Salazar",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 9,
    "Nivel": "FPA 1\nU7",
    "Repertorio": "1. Tengo una muñeca  \n2. El riachuleo alegre \n3. Yankee Doddle \n4. Himno de la alegría",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 5,
    "Nombre": "Edwin Daniel Figueroa Ovando",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 7,
    "Nivel": "FPA 1\nU1",
    "Repertorio": "5. El granjero\n6. Dos por diez\n7. Remando por el mar\n8. Brillan las estrellas",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nPendiente",
    "Boletos \nExtras": "No",
    "Pago": "Pagado"
  },
  {
    "": 6,
    "Nombre": "Ximena Álvarez Díaz",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 11,
    "Nivel": "FPA 2\nTERMINADO",
    "Repertorio": "1. Pequeña serenata nocturna (pieza libre)\n2. Dos pequeñas marchas: un desfile bajo el sol y un desfile bajo la lluvia .\n3. Una melodía de Beethoven \n4. Sonatina en miniatura: Primer y Segundo Movimiento \n5. Yo siento el ritmo \n6. El espantapájaros ",
    "Duración": 5,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": 1,
    "Pago": "Pagado"
  },
  {
    "": 7,
    "Nombre": "Jimena Guadalupe Naal Puc",
    "Escuela": "Clapping",
    "Docente": "Andrea",
    "Edad": 14,
    "Nivel": "Faber Adultos\nTerminando",
    "Repertorio": "1. Una melodía de 500 años\n2. Greensleeves\n3. Danza polovetsiana\n4. Los patinadores",
    "Duración": 5,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": 6,
    "Pago": "Pagado"
  },
  {
    "": 8,
    "Nombre": "Shaina Celeste Pérez Cardeña",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 10,
    "Nivel": "FPA 2\nU1",
    "Repertorio": "4. El cazador\n5. El arcoiris\n6. El potro salvaje\n7. El ratoncito busca el queso",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "1 cuota"
  },
  {
    "": 9,
    "Nombre": "Isabella Cabrera Salazar",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 9,
    "Nivel": "FPA 1\nU7",
    "Repertorio": "5. Bridal chorus\n6. Parte de él (Sirenita) \n7. Can-Can\n8. Little Night Music",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 10,
    "Nombre": "Ximena Álvarez Díaz",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 11,
    "Nivel": "FPA 2\nTERMINADO",
    "Repertorio": "7. Viaje en Camello \n8. Príncipe Sapo \n9. La danza del dinosaurio \n10. El puente de Aviñón \n11. El tranvía \n12. El globo de chicle",
    "Duración": 5,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": 1,
    "Pago": "Pagado"
  },
  {
    "": 11,
    "Nombre": "Lena Priscila Diaz Escalante",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 9,
    "Nivel": "FPA 1\nTERMINADO",
    "Repertorio": "4. Lluvia, ¡vete ya! \n5. Gran celebración \n6. Let it be, dueto con José Diaz (papá)",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes\n9",
    "Pago": "Pagado"
  },
  {
    "": 12,
    "Nombre": "Jimena Guadalupe Naal Puc",
    "Escuela": "Clapping",
    "Docente": "Andrea",
    "Edad": 14,
    "Nivel": "Faber Adultos\nTerminando",
    "Repertorio": "5. Marcha de la guardia inglesa\n6. Tema del concierto para trompeta\n7. Banuwa\n8. El carnaval de Venecia",
    "Duración": 4,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": 6,
    "Pago": "Pagado"
  },
  {
    "": 13,
    "Nombre": "Shaina Celeste Pérez Cardeña",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": 10,
    "Nivel": "FPA 2\nU1",
    "Repertorio": "8. Vamos a navegar\n9. El ratoncito de la casa embrujada\n10. El estudio de legato\n11. Marcha",
    "Duración": 5,
    "Horario \nAsinagdo": "7:00\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "1 cuota"
  },
]
recital4 = [
  {
    "": 1,
    "Nombre": "Armando Francisco Bojórquez Tejeda",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 1\nU7",
    "Repertorio": "1. Mi invento\n2. Estrellita\n3. Marcha en re mi fa\n4. Tocando con la banda\n5. Pequeño minué",
    "Duración": 5,
    "Horario \nAsinagdo": "8:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pendiente"
  },
  {
    "": 2,
    "Nombre": "Yiré Zoán Vázquez Ramírez",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 2\nU1",
    "Repertorio": "1. Vamos a navegar\n2. El ratoncito de la casa embrujada\n3. El estudio de legato\n4. Danza clásica",
    "Duración": 5,
    "Horario \nAsinagdo": "8:30\nPendiente",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pagado"
  },
  {
    "": 3,
    "Nombre": "Rodrigo Alejandro Aguayo Lara",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 3\nU4",
    "Repertorio": "1. El Sr. McGill \n2. Danza de los marineros rusos\n3. Detectives privados",
    "Duración": 5,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pendiente"
  },
  {
    "": 4,
    "Nombre": "Axel Sebastián García Martínez",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 6,
    "Nivel": "Deditos",
    "Repertorio": "1. Campanas\n2. La lluvia \n3. Lupe y Roberto \n4. A mi trineo",
    "Duración": 5,
    "Horario \nAsinagdo": "8:30\nConfirmado",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pendiente"
  },
  {
    "": 5,
    "Nombre": "Armando Francisco Bojórquez Tejeda",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 1\nU7",
    "Repertorio": "6. Vamos a jugar\n7. Carnaval\n8. Ronda del abedul\n9. Ven a ver el desfile\n10.Tema con variaciones",
    "Duración": 5,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pendiente"
  },
  {
    "": 6,
    "Nombre": "Carolina Maldonado Cruz",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 10,
    "Nivel": "Thomson grado 1",
    "Repertorio": "1. Campanas de Escocia\n2. El amolador\n3. Los cisnes en el lago \n4. Gorrión gorrión",
    "Duración": 8,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pagado $650"
  },
  {
    "": 7,
    "Nombre": "Isabella",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 5,
    "Nivel": "Deditos terminado +",
    "Repertorio": "1. La abeja\n2. Tambores indios \n3. Cuídate mago\n4. Melodía\n5. Mi novia",
    "Duración": 4,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pagado $650"
  },
  {
    "": 8,
    "Nombre": "Yiré Zoán Vázquez Ramírez",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 2\nU1",
    "Repertorio": "5. La luciérnaga\n6. La rueda de la fortuna\n7. El cazador\n8. El ratoncito busca el queso\n9. Marcha turca",
    "Duración": 5,
    "Horario \nAsinagdo": "8:30\nConfirmado",
    "Boletos \nExtras": 0,
    "Pago": "Pendiente"
  },
  {
    "": 9,
    "Nombre": "Janice Montero Probando",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 20,
    "Nivel": "Thomson grado 1",
    "Repertorio": "1. Stepping Stones\n2. The Robin\n3. Chord Frolic",
    "Duración": 6,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pendiente"
  },
  {
    "": 10,
    "Nombre": "Lizeth Rojas",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 41,
    "Nivel": "Thomson grado 1",
    "Repertorio": "1. Swans on the lake \n2. The man in the moon\n3. Stepping stones",
    "Duración": 6,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pagado $650"
  },
  {
    "": 11,
    "Nombre": "Isabella Santos",
    "Escuela": "Orquestarte",
    "Docente": "David",
    "Edad": 5,
    "Nivel": "Deditos terminado +",
    "Repertorio": "6. Canción de los boteros\n7. Lupe y Roberto\n8. Mi rancho en los llanos \n9. The married life",
    "Duración": 7,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": "Pagado $650"
  },
  {
    "": 12,
    "Nombre": "Rodrigo Alejandro Aguayo Lara",
    "Escuela": "Clapping",
    "Docente": "Arleni",
    "Edad": "",
    "Nivel": "FPA 3\nU4",
    "Repertorio": "4. El canto de la selva \n5. Tormentas de Saturno\n6. Let it be",
    "Duración": 5,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "Pendientes",
    "Pago": "Pendiente"
  },
  {
    "": "",
    "Nombre": "Arleni y David",
    "Escuela": "",
    "Docente": "",
    "Edad": "",
    "Nivel": "",
    "Repertorio": "El jardín encantado",
    "Duración": 3,
    "Horario \nAsinagdo": "",
    "Boletos \nExtras": "",
    "Pago": ""
  },
]